// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPA90gxwLv4P27Cu09UhRIhKjLm5b_Mgw',
    appId: '1:68404960270:web:64e72dc79bf00f770fb05f',
    messagingSenderId: '68404960270',
    projectId: 'flutter-random-1',
    authDomain: 'flutter-random-1.firebaseapp.com',
    storageBucket: 'flutter-random-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWz6pMpQHIM30hWFZRus4KdsTIs_bINvw',
    appId: '1:68404960270:android:071654c04bb868630fb05f',
    messagingSenderId: '68404960270',
    projectId: 'flutter-random-1',
    storageBucket: 'flutter-random-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm0mix_sozjgYzS5ZP1A6OvDiyDtqV2xs',
    appId: '1:68404960270:ios:a63b65a4332b4f7b0fb05f',
    messagingSenderId: '68404960270',
    projectId: 'flutter-random-1',
    storageBucket: 'flutter-random-1.appspot.com',
    iosClientId: '68404960270-u84d00kh386khc1crsmvaoc538cmfqfm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm0mix_sozjgYzS5ZP1A6OvDiyDtqV2xs',
    appId: '1:68404960270:ios:a63b65a4332b4f7b0fb05f',
    messagingSenderId: '68404960270',
    projectId: 'flutter-random-1',
    storageBucket: 'flutter-random-1.appspot.com',
    iosClientId: '68404960270-u84d00kh386khc1crsmvaoc538cmfqfm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
